var GLOBAL_VERSION = 2.3;

$(function () {
  // Glossary data is pre-loaded via data/glossary.js; just init tooltips
  Glossary.init();

  $('.global-version-badge').text('Global v' + GLOBAL_VERSION);

  // Mobile slide-out drawer
  var $drawer = $('#navDrawer');
  var $overlay = $('#navOverlay');

  function openDrawer() {
    $drawer.addClass('open');
    $overlay.addClass('open');
    $('body').css('overflow', 'hidden');
  }

  function closeDrawer() {
    $drawer.removeClass('open');
    $overlay.removeClass('open');
    $('body').css('overflow', '');
  }

  $('#navToggle').on('click', openDrawer);
  $('#navClose').on('click', closeDrawer);
  $overlay.on('click', closeDrawer);
  $drawer.on('click', '[data-page]', closeDrawer);

  // Close drawer if viewport grows past mobile breakpoint
  $(window).on('resize', function () {
    if (window.innerWidth >= 768) closeDrawer();
  });

  // "Misc." nav dropdown — the toggle itself doesn't navigate anywhere,
  // it just reveals a menu of actual pages (e.g. Dispatch Table).
  var $miscDropdown = $('#miscDropdown');

  $('#miscDropdownToggle').on('click', function (e) {
    e.preventDefault();
    $miscDropdown.toggleClass('open');
  });

  $(document).on('click', function (e) {
    if (!$(e.target).closest('#miscDropdown').length) {
      $miscDropdown.removeClass('open');
    }
  });

  $miscDropdown.on('click', '.nav-dropdown-item', function () {
    $miscDropdown.removeClass('open');
  });


  var DEFAULT_PAGE = 'pilots';
  var currentPage  = null;

  // ── URLs ───────────────────────────────────────────────────────────────────
  // Routes are written internally as "#page/param" (all existing hrefs use
  // that form), but the address bar shows path URLs like "pilots/ada/" so a
  // copied link hits a real file generated by build_pages.py — that file
  // carries the item's own og:/twitter: preview tags for Facebook/Discord.
  // Routes without a generated file (e.g. "#builder/<UID>") stay as hashes.

  // Param of every item that has a generated detail page, per route. Must
  // match the item lists in build_pages.py.
  var DETAIL_PARAMS = {
    pilots:    function () { return ((window.PilotsData || {}).pilots || []).map(function (p) { return p.PilotName; }); },
    sts:       function () { return ((window.MechsData || {}).mechs || []).map(function (m) { return m.name; }); },
    weapons:   function () {
      return ((window.WeaponsData || {}).weapons || [])
        .filter(function (w) { return w.quality === 'SSSR' && w.version; })
        .map(function (w) { return w.name; });
    },
    backpacks: function () { return ((window.BackpacksData || {}).backpacks || []).map(backpackSlug); },
    modules:   function () {
      var modules = (window.ModulesData || {}).modules || {};
      return Object.keys(modules).map(function (fam) { return modules[fam].name.toLowerCase(); });
    },
  };

  // Must match slugify() in build_pages.py.
  function slugify(s) {
    return String(s).normalize('NFKD').replace(/\p{M}/gu, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  }

  function parseRoute(hash) {
    var raw   = hash.replace(/^#\/?/, '');
    var slash = raw.indexOf('/');
    if (slash === -1) return { page: raw || DEFAULT_PAGE, param: null };
    return { page: raw.slice(0, slash), param: decodeURIComponent(raw.slice(slash + 1)) || null };
  }

  // Path of the current URL relative to the site root (the <base> href).
  function relativePath() {
    var root = new URL(document.baseURI).pathname;
    var path = window.location.pathname;
    return path.indexOf(root) === 0 ? path.slice(root.length) : path.replace(/^\//, '');
  }

  function currentRoute() {
    if (window.location.hash.length > 1) return parseRoute(window.location.hash);
    var parts = relativePath().split('/').filter(Boolean);
    var page  = parts[0] || DEFAULT_PAGE;
    var param = null;
    if (parts[1]) {
      var slug = decodeURIComponent(parts[1]);
      var all  = DETAIL_PARAMS[page] ? DETAIL_PARAMS[page]() : [];
      param = all.find(function (p) { return slugify(p) === slug; }) || slug;
    }
    return { page: page, param: param };
  }

  function urlFor(page, param) {
    if (!param) return page === DEFAULT_PAGE ? './' : page + '/';
    if (DETAIL_PARAMS[page]) return page + '/' + slugify(param) + '/';
    return './#' + page + '/' + encodeURIComponent(param);
  }

  // Navigate to a "#page/param" route, adding a history entry.
  function go(hash) {
    var r = parseRoute(hash);
    history.pushState(null, '', urlFor(r.page, r.param));
    navigate(r.page, r.param);
  }

  // Render whatever the address bar points at, normalising legacy
  // "#pilots/Ada"-style links to their path form without a new history entry.
  function routeFromLocation() {
    var r = currentRoute();
    var canonical = new URL(urlFor(r.page, r.param), document.baseURI).href;
    if (Pages[r.page] && canonical !== window.location.href) history.replaceState(null, '', canonical);
    navigate(r.page, r.param);
  }

  window.App = {
    go: go,
    // Absolute shareable URL for a route.
    url: function (page, param) { return new URL(urlFor(page, param), document.baseURI).href; },
  };

  // Hash-only links would otherwise resolve against <base> (the site root)
  // and reload the page whenever the current URL is a sub-path.
  $(document).on('click', 'a[href^="#"]', function (e) {
    if (e.isDefaultPrevented() || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    e.preventDefault();
    var href = $(this).attr('href');
    var r    = parseRoute(href);
    if (href.length > 1 && Pages[r.page]) {
      go(href);
    } else if (href.length > 1) {
      var el = document.getElementById(href.slice(1));
      if (el) el.scrollIntoView();
    }
  });

  function navigate(page, param) {
    var p = Pages[page];
    if (!p) {
      $('#app-content').html('<p class="text-danger">Page not found.</p>');
      return;
    }

    if (currentPage && Pages[currentPage] && Pages[currentPage].destroy) {
      Pages[currentPage].destroy();
    }
    currentPage = page;

    $('[data-page]').removeClass('active');
    $('[data-page="' + page + '"]').addClass('active');
    $('#miscDropdownToggle').toggleClass('active', page === 'dispatch' || page === 'exskills' || page === 'shops' || page === 'ststats' || page === 'pilotstats' || page === 'builder');

    // Pages expect the param still URI-encoded, as it used to come straight from the hash.
    $('#app-content').html(p.render(param == null ? null : encodeURIComponent(param)));
    window.scrollTo(0, 0);

    document.title = p.title + ' — Mecharashi Wiki';
  }

  $(window).on('popstate', routeFromLocation);

  routeFromLocation();
});
